<#
.SYNOPSIS
Runs DISM ScanHealth and returns a structured result.
#>
[CmdletBinding()]
Param([Parameter(Mandatory=$false)][ValidateSet('Object','Json','None')][string]$OutputFormat='Object',[Parameter(Mandatory=$false)][string]$LogPath,[Parameter(Mandatory=$false)][string]$ResultPath,[Parameter(Mandatory=$false)][switch]$Quiet)
function ConvertTo-SingleQuotedArgument{Param([string]$Value)if($null -eq $Value){return "''"};return("'{0}'" -f ($Value -replace "'","''"))}
function Get-RelayParameterText{$parts=@();$parts+=('-OutputFormat {0}' -f (ConvertTo-SingleQuotedArgument $OutputFormat));if($LogPath){$parts+=('-LogPath {0}' -f (ConvertTo-SingleQuotedArgument $LogPath))};if($ResultPath){$parts+=('-ResultPath {0}' -f (ConvertTo-SingleQuotedArgument $ResultPath))};if($Quiet){$parts+='-Quiet'};return($parts -join ' ')}
if([Environment]::Is64BitOperatingSystem -and -not[Environment]::Is64BitProcess){$p=Join-Path $env:WINDIR 'Sysnative\WindowsPowerShell\v1.0\powershell.exe';if(-not(Test-Path $p)){Write-Error '64-bit PowerShell is required, but Sysnative Windows PowerShell was not found.';exit 3};if($PSCommandPath){$cmd=('& {0} {1}' -f (ConvertTo-SingleQuotedArgument $PSCommandPath),(Get-RelayParameterText))}else{$dir=Join-Path $env:TEMP 'AUT-WindowsHealth-Relay';if(-not(Test-Path $dir)){New-Item $dir -ItemType Directory -Force|Out-Null};$relay=Join-Path $dir ('Invoke-DismScanHealth-{0}.ps1' -f ([guid]::NewGuid().ToString('N')));Set-Content $relay $MyInvocation.MyCommand.ScriptBlock.ToString() -Encoding UTF8;$cmd=('& {0} {1}' -f (ConvertTo-SingleQuotedArgument $relay),(Get-RelayParameterText))};try{$proc=Start-Process $p -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-Command',$cmd) -Wait -PassThru -WindowStyle Hidden;exit $proc.ExitCode}finally{if($relay -and(Test-Path $relay)){Remove-Item $relay -Force -ErrorAction SilentlyContinue}}}
$ScriptName='Invoke-DismScanHealth';$Operation='DismScanHealth';$Timestamp=Get-Date -Format 'yyyyMMdd-HHmmss';$LogRoot='C:\Temp\Logs';if(-not(Test-Path $LogRoot)){New-Item $LogRoot -ItemType Directory -Force|Out-Null};if([string]::IsNullOrWhiteSpace($LogPath)){$LogPath=Join-Path $LogRoot ('{0}-{1}.log' -f $ScriptName,$Timestamp)};$resultsDir=Join-Path $LogRoot 'results';if(-not(Test-Path $resultsDir)){New-Item $resultsDir -ItemType Directory -Force|Out-Null};if([string]::IsNullOrWhiteSpace($ResultPath)){$ResultPath=Join-Path $resultsDir ('{0}-result-{1}.json' -f $ScriptName,$Timestamp)};$script:LogPath=$LogPath
function Write-Log{Param([string]$Message,[ValidateSet('Debug','Information','Warning','Error')][string]$Level='Information')Add-Content $script:LogPath ('{0} [{1}] [{2}] {3}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'),$Level,$Operation,$Message) -Encoding UTF8}
function Test-Administrator{$id=[Security.Principal.WindowsIdentity]::GetCurrent();$pr=New-Object Security.Principal.WindowsPrincipal($id);return $pr.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-NativeOutputPath{Param([string]$OperationName,[string]$OutputTimestamp)$ld=Split-Path $script:LogPath -Parent;if([string]::IsNullOrWhiteSpace($ld)){$ld='C:\Temp\Logs'};$sd=Join-Path $ld 'scan-results';if(-not(Test-Path $sd)){New-Item $sd -ItemType Directory -Force|Out-Null};return(Join-Path $sd ('{0}-{1}.txt' -f $OperationName,$OutputTimestamp))}
function Test-OutputPattern{Param([string]$Text,[string]$Pattern)if($null -eq $Text){return $false};$cleanText=$Text.Replace([char]0,'');if($cleanText -match [regex]::Escape($Pattern)){return $true};return(($cleanText -replace '\s','') -match [regex]::Escape(($Pattern -replace '\s','')))}
function New-ErrorObject{Param([string]$Message,[string]$RecommendedAction)return [pscustomobject]@{Target='LocalComputer';Operation=$Operation;Message=$Message;Category='Execution';RecommendedAction=$RecommendedAction}}
function Complete-Script{Param([pscustomobject]$Result)$Result|ConvertTo-Json -Depth 8|Set-Content $Result.ResultPath -Encoding UTF8;Write-Log ('Completed status={0}; exit={1}; nativeExit={2}; rawStatus={3}; recommendedAction={4}; nativeOutput={5}; result={6}.' -f $Result.Status,$Result.ExitCode,$Result.Data.ToolExitCode,$Result.Data.RawStatus,$Result.RecommendedAction,$Result.Data.NativeOutputPath,$Result.ResultPath);switch($OutputFormat){'Json'{$Result|ConvertTo-Json -Depth 8 -Compress}'Object'{Write-Output $Result}'None'{}};exit $Result.ExitCode}
$result=[pscustomobject]@{ScriptName=$ScriptName;Operation=$Operation;Status='Failed';ExitCode=1;Changed=$false;Message='DISM ScanHealth did not complete.';LogPath=$LogPath;ResultPath=$ResultPath;RecommendedAction='ReviewLog';Data=[pscustomobject]@{ToolExitCode=$null;RawStatus='Unknown';CorruptionDetected=$false;Repairable=$false;DismScanRequired=$false;DismRestoreRequired=$false;SfcRequired=$false;NativeOutputPath=$null;Is64BitProcess=[Environment]::Is64BitProcess};Errors=@()}
Write-Log 'Starting DISM ScanHealth.';if(-not(Test-Administrator)){$result.Status='DependencyMissing';$result.ExitCode=3;$result.Message='Administrative elevation is required.';$result.RecommendedAction='RunElevated';$result.Errors+=New-ErrorObject $result.Message 'RunElevated';Complete-Script $result};$dism=Join-Path $env:WINDIR 'System32\dism.exe';if(-not(Test-Path $dism)){$result.Status='DependencyMissing';$result.ExitCode=3;$result.Message='dism.exe was not found.';$result.RecommendedAction='ReviewWindowsInstallation';$result.Errors+=New-ErrorObject $result.Message 'ReviewWindowsInstallation';Complete-Script $result};$out=Get-NativeOutputPath $Operation $Timestamp;$result.Data.NativeOutputPath=$out;Write-Log ('Executing DISM /Online /Cleanup-Image /ScanHealth; nativeOutput={0}.' -f $out);& $dism /Online /Cleanup-Image /ScanHealth *> $out;$result.Data.ToolExitCode=$LASTEXITCODE;Write-Log ('DISM ScanHealth native exit code={0}.' -f $result.Data.ToolExitCode);$text=Get-Content $out -Raw -ErrorAction SilentlyContinue
if(Test-OutputPattern $text 'No component store corruption detected'){$result.Status='NoActionNeeded';$result.ExitCode=0;$result.Message='No component store corruption detected.';$result.RecommendedAction='RunSfcScan';$result.Data.RawStatus='NoCorruption';$result.Data.SfcRequired=$true}elseif(Test-OutputPattern $text 'The component store is repairable'){$result.Status='Success';$result.ExitCode=0;$result.Message='The component store is repairable.';$result.RecommendedAction='RunDismRestoreHealth';$result.Data.RawStatus='Repairable';$result.Data.CorruptionDetected=$true;$result.Data.Repairable=$true;$result.Data.DismRestoreRequired=$true}elseif(Test-OutputPattern $text 'The component store cannot be repaired'){$result.Status='Failed';$result.ExitCode=1;$result.Message='The component store cannot be repaired.';$result.RecommendedAction='ManualRepairRequired';$result.Data.RawStatus='NotRepairable';$result.Data.CorruptionDetected=$true;$result.Errors+=New-ErrorObject $result.Message 'ManualRepairRequired'}elseif($result.Data.ToolExitCode -ne 0){$result.Status='Failed';$result.ExitCode=1;$result.Message=('DISM ScanHealth failed with native exit code {0}.' -f $result.Data.ToolExitCode);$result.RecommendedAction='ReviewLog';$result.Errors+=New-ErrorObject $result.Message 'ReviewLog'}else{$result.Message='Unable to determine DISM ScanHealth status from output.';$result.Errors+=New-ErrorObject $result.Message 'ReviewLog'};Write-Log ('Classified ScanHealth as {0}: {1}' -f $result.Data.RawStatus,$result.Message);Complete-Script $result
