<#
.SYNOPSIS
Runs DISM RestoreHealth and returns a structured result.
#>
[CmdletBinding()]
Param([Parameter(Mandatory=$false)][ValidateSet('Object','Json','None')][string]$OutputFormat='Object',[Parameter(Mandatory=$false)][string]$LogPath,[Parameter(Mandatory=$false)][string]$ResultPath,[Parameter(Mandatory=$false)][switch]$Quiet)
function ConvertTo-SingleQuotedArgument{Param([string]$Value) if($null -eq $Value){return "''"}; return ("'{0}'" -f ($Value -replace "'", "''"))}
function Get-RelayParameterText{$parts=@();$parts+=('-OutputFormat {0}' -f (ConvertTo-SingleQuotedArgument $OutputFormat));if($LogPath){$parts+=('-LogPath {0}' -f (ConvertTo-SingleQuotedArgument $LogPath))};if($ResultPath){$parts+=('-ResultPath {0}' -f (ConvertTo-SingleQuotedArgument $ResultPath))};if($Quiet){$parts+='-Quiet'};return($parts -join ' ')}
if([Environment]::Is64BitOperatingSystem -and -not [Environment]::Is64BitProcess){$p=Join-Path $env:WINDIR 'Sysnative\WindowsPowerShell\v1.0\powershell.exe';if(-not(Test-Path -LiteralPath $p -PathType Leaf)){Write-Error '64-bit PowerShell is required, but Sysnative Windows PowerShell was not found.';exit 3};if($PSCommandPath){$cmd=('& {0} {1}' -f (ConvertTo-SingleQuotedArgument $PSCommandPath),(Get-RelayParameterText))}else{$dir=Join-Path $env:TEMP 'AUT-WindowsHealth-Relay';if(-not(Test-Path -LiteralPath $dir -PathType Container)){New-Item -Path $dir -ItemType Directory -Force|Out-Null};$relay=Join-Path $dir ('Invoke-DismRestoreHealth-{0}.ps1' -f ([Guid]::NewGuid().ToString('N')));Set-Content -LiteralPath $relay -Value $MyInvocation.MyCommand.ScriptBlock.ToString() -Encoding UTF8;$cmd=('& {0} {1}' -f (ConvertTo-SingleQuotedArgument $relay),(Get-RelayParameterText))};try{$proc=Start-Process -FilePath $p -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-Command',$cmd) -Wait -PassThru -WindowStyle Hidden;exit $proc.ExitCode}finally{if($relay -and (Test-Path -LiteralPath $relay -PathType Leaf)){Remove-Item -LiteralPath $relay -Force -ErrorAction SilentlyContinue}}}
$ScriptName='Invoke-DismRestoreHealth';$Operation='DismRestoreHealth';$Timestamp=Get-Date -Format 'yyyyMMdd-HHmmss';if([string]::IsNullOrWhiteSpace($LogPath)){$LogPath=Join-Path 'C:\Temp' ('{0}-{1}.log' -f $ScriptName,$Timestamp)};$script:LogPath=$LogPath
function Write-Log{Param([string]$Message,[ValidateSet('Debug','Information','Warning','Error')][string]$Level='Information')$d=Split-Path $script:LogPath -Parent;if($d -and -not(Test-Path -LiteralPath $d -PathType Container)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Add-Content -LiteralPath $script:LogPath -Value ('{0} [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'),$Level,$Message) -Encoding UTF8}
function Test-Administrator{$id=[Security.Principal.WindowsIdentity]::GetCurrent();$pr=New-Object Security.Principal.WindowsPrincipal($id);return $pr.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Get-NativeOutputPath{Param([string]$OperationName,[string]$OutputTimestamp)$ld=Split-Path $script:LogPath -Parent;if([string]::IsNullOrWhiteSpace($ld)){$ld='C:\Temp'};$sd=Join-Path $ld 'scan-results';if(-not(Test-Path -LiteralPath $sd -PathType Container)){New-Item -Path $sd -ItemType Directory -Force|Out-Null};return(Join-Path $sd ('{0}-{1}.txt' -f $OperationName,$OutputTimestamp))}
function Test-OutputPattern{Param([string]$Text,[string]$Pattern)if($Text -match [regex]::Escape($Pattern)){return $true};if(($Text -replace '\s','') -match [regex]::Escape(($Pattern -replace '\s',''))){return $true};return $false}
function New-ErrorObject{Param([string]$Message,[string]$RecommendedAction)return [pscustomobject]@{Target='LocalComputer';Operation=$Operation;Message=$Message;Category='Execution';RecommendedAction=$RecommendedAction}}
function Export-ServicingDiagnostics{
    Param([datetime]$OperationStartTime,[string]$OutputTimestamp)
    $artifacts=@();$logDirectory=Split-Path $script:LogPath -Parent;if([string]::IsNullOrWhiteSpace($logDirectory)){$logDirectory='C:\Temp'};if(-not(Test-Path -LiteralPath $logDirectory -PathType Container)){New-Item -Path $logDirectory -ItemType Directory -Force|Out-Null};$prefix=Join-Path $logDirectory ('{0}-{1}' -f $Operation,$OutputTimestamp)
    $cbsPath=Join-Path $env:WINDIR 'Logs\CBS\CBS.log';$dismLogPath=Join-Path $env:WINDIR 'Logs\DISM\dism.log';$sessionsPath=Join-Path $env:WINDIR 'servicing\Sessions\Sessions.xml'
    foreach($item in @(@{Source=$cbsPath;Destination=($prefix+'-CBS-tail.txt');Tail=100},@{Source=$dismLogPath;Destination=($prefix+'-DISM-tail.txt');Tail=100})){
        try{if(Test-Path -LiteralPath $item.Source -PathType Leaf){Get-Content -LiteralPath $item.Source -Tail $item.Tail -ErrorAction Stop|Set-Content -LiteralPath $item.Destination -Encoding UTF8;$artifacts+=$item.Destination}}
        catch{Write-Log ('Unable to capture servicing log tail from {0}: {1}' -f $item.Source,$_.Exception.Message) 'Warning'}
    }
    try{if(Test-Path -LiteralPath $cbsPath -PathType Leaf){$filtered=$prefix+'-CBS-errors.txt';Get-Content -LiteralPath $cbsPath -Tail 2000 -ErrorAction Stop|Select-String -Pattern 'Error|CORRUPT|MISSING|HRESULT'|ForEach-Object{$_.Line}|Set-Content -LiteralPath $filtered -Encoding UTF8;if(Test-Path -LiteralPath $filtered -PathType Leaf){$artifacts+=$filtered}}}
    catch{Write-Log ('Unable to capture filtered CBS diagnostics: {0}' -f $_.Exception.Message) 'Warning'}
    try{if(Test-Path -LiteralPath $sessionsPath -PathType Leaf){$sessionsDestination=$prefix+'-Sessions.xml';Copy-Item -LiteralPath $sessionsPath -Destination $sessionsDestination -Force -ErrorAction Stop;$artifacts+=$sessionsDestination}}
    catch{Write-Log ('Unable to capture servicing Sessions.xml: {0}' -f $_.Exception.Message) 'Warning'}
    $eventStart=$OperationStartTime.AddMinutes(-5);$eventQueries=@(@{Name='Servicing-Operational';LogName='Microsoft-Windows-Servicing/Operational';Provider=$null},@{Name='System-Servicing';LogName='System';Provider='Microsoft-Windows-Servicing'},@{Name='WindowsUpdateClient-Operational';LogName='Microsoft-Windows-WindowsUpdateClient/Operational';Provider=$null},@{Name='System-WindowsUpdateClient';LogName='System';Provider='Microsoft-Windows-WindowsUpdateClient'})
    foreach($query in $eventQueries){try{$available=Get-WinEvent -ListLog $query.LogName -ErrorAction SilentlyContinue;if($null -eq $available){continue};$filter=@{LogName=$query.LogName;StartTime=$eventStart;Level=@(1,2,3)};if($query.Provider){$filter.ProviderName=$query.Provider};$events=@(Get-WinEvent -FilterHashtable $filter -ErrorAction Stop|Sort-Object TimeCreated -Descending|Select-Object -First 100);if($events.Count -gt 0){$eventPath=$prefix+'-'+$query.Name+'-events.txt';$events|Select-Object TimeCreated,Id,LevelDisplayName,ProviderName,Message|Format-List|Out-String -Width 4096|Set-Content -LiteralPath $eventPath -Encoding UTF8;$artifacts+=$eventPath}}catch{Write-Log ('Unable to capture {0} events: {1}' -f $query.Name,$_.Exception.Message) 'Warning'}}
    Write-Log ('Captured {0} servicing diagnostic artifact(s).' -f $artifacts.Count);return @($artifacts)
}
function Complete-Script{Param([pscustomobject]$Result)if($Result.ResultPath){$rd=Split-Path $Result.ResultPath -Parent;if($rd -and -not(Test-Path -LiteralPath $rd -PathType Container)){New-Item -Path $rd -ItemType Directory -Force|Out-Null};$Result|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $Result.ResultPath -Encoding UTF8};Write-Log ('Completed with status {0}, exit code {1}. {2}' -f $Result.Status,$Result.ExitCode,$Result.Message);switch($OutputFormat){'Json'{$Result|ConvertTo-Json -Depth 8 -Compress}'Object'{Write-Output $Result}'None'{}};exit $Result.ExitCode}
$result=[pscustomobject]@{ScriptName=$ScriptName;Operation=$Operation;Status='Failed';ExitCode=1;Changed=$false;Message='DISM RestoreHealth did not complete.';LogPath=$LogPath;ResultPath=$ResultPath;RecommendedAction='ReviewLog';Data=[pscustomobject]@{ToolExitCode=$null;RawStatus='Unknown';RestoreCompleted=$false;NativeOutputPath=$null;DiagnosticArtifacts=@();Is64BitProcess=[Environment]::Is64BitProcess};Errors=@()}
Write-Log 'Starting DISM RestoreHealth.';if(-not(Test-Administrator)){$result.Status='DependencyMissing';$result.ExitCode=3;$result.Message='Administrative elevation is required.';$result.RecommendedAction='RunElevated';$result.Errors+=New-ErrorObject $result.Message 'RunElevated';Complete-Script $result}
$dism=Join-Path $env:WINDIR 'System32\dism.exe';if(-not(Test-Path -LiteralPath $dism -PathType Leaf)){$result.Status='DependencyMissing';$result.ExitCode=3;$result.Message='dism.exe was not found.';$result.RecommendedAction='ReviewWindowsInstallation';$result.Errors+=New-ErrorObject $result.Message 'ReviewWindowsInstallation';Complete-Script $result}
$operationStartTime=Get-Date
$out=Get-NativeOutputPath $Operation $Timestamp;$result.Data.NativeOutputPath=$out;& $dism /Online /Cleanup-Image /RestoreHealth *> $out;$result.Data.ToolExitCode=$LASTEXITCODE;$text=Get-Content -LiteralPath $out -Raw -ErrorAction SilentlyContinue
if($result.Data.ToolExitCode -eq 0 -and ((Test-OutputPattern $text 'The restore operation completed successfully') -or (Test-OutputPattern $text 'The operation completed successfully'))){$result.Status='Changed';$result.ExitCode=0;$result.Changed=$true;$result.Message='DISM RestoreHealth completed successfully.';$result.RecommendedAction='RunSfcScan';$result.Data.RawStatus='Success';$result.Data.RestoreCompleted=$true}
elseif($result.Data.ToolExitCode -ne 0){$result.Status='Failed';$result.ExitCode=1;$result.Message=('DISM RestoreHealth failed with native exit code {0}.' -f $result.Data.ToolExitCode);$result.RecommendedAction='ReviewServicingDiagnostics';$result.Data.DiagnosticArtifacts=@(Export-ServicingDiagnostics -OperationStartTime $operationStartTime -OutputTimestamp $Timestamp);$result.Errors+=New-ErrorObject $result.Message 'ReviewServicingDiagnostics'}else{$result.Message='Unable to determine DISM RestoreHealth status from output.';$result.RecommendedAction='ReviewServicingDiagnostics';$result.Data.DiagnosticArtifacts=@(Export-ServicingDiagnostics -OperationStartTime $operationStartTime -OutputTimestamp $Timestamp);$result.Errors+=New-ErrorObject $result.Message 'ReviewServicingDiagnostics'}
Complete-Script $result
